# https://www.mkdocs.org/getting-started/
site_name: Math Tools Demo
site_description: A demo package for testing documentation
repo_url: https://github.com/edoardodraetta/docs-demo-mkdocs

# Material theme block
# theme:
#   name: material
#   palette:
#     primary: indigo
#   features:
#     - navigation.tabs
#     # - navigation.sections # Disable to collapse

# RTD theme block
theme:
  name: readthedocs

nav:
  - Home: index.md
  - Installation: installation.md
  - Quick Start: quickstart.md
  - Tutorials:
    - Overview: tutorials/tutorials.md
    - Basic Operations: tutorials/basic_operations.ipynb
  - API Reference:
    - Overview: api/index.md
    - Core:
        - Math Tools: api/math_tools.md
        - Statistics: api/statistics.md
    - Advanced:
        - Overview: api/advanced/index.md
        - Calculus: api/advanced/calculus.md
        - Linear Algebra: api/advanced/linear_algebra.md

plugins:
  - search
  - mkdocstrings: # mkdocstrings will automatically generate API reference pages
      handlers:
        python:
          options:
            show_source: true
  - mkdocs-jupyter:
      include_source: True